version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - sudo yum install -y openjdk-7-jdk
      - yum install maven2 -y
      - mvn clean install
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t testrepo .
      - docker tag testrepo:latest 555466333143.dkr.ecr.us-east-1.amazonaws.com/testrepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 555466333143.dkr.ecr.us-east-1.amazonaws.com/testrepo:latest
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
